#include <M5StickC.h> 
#include <WiFi.h> 
TFT_eSprite img = TFT_eSprite(&M5.Lcd);
// setup button values 
int last_val = 0;
int cur_val = 0; 
char ssid[] = "WhiteCat"; 
char pass[] = "whitecat1"; 
WiFiServer server(80); 
byte mac[] = { 0x24, 0xA1, 0x60, 0x53, 0xC5, 0xF4 };
#define IW 320 
#define IH 40
#define WAIT 45
#define XX 5700
#define AX 230
#define IW2 50
#define IH2 50
#define A 37
#define B 39

unsigned int CRT(byte value) { 
// Do random color as byte value
byte red_blue_green = random(0xFFFF);
return red_blue_green * value;  
}

unsigned int RGBVAL(byte value) {
  byte red = 0;  // Do basic color wheel by switch sector
  byte blue = 0;
  byte green = 0;

  byte sector = value >> 5;
  byte amplit = value & 0x1F;

  switch (sector) {
  case 0: 
  red = 0x1F;
  green = amplit;
  blue = 0;
  break;
  case 1:
  red = 0x1F - amplit;
  green = 0x1F;
  blue = 0;
  break;
  case 2:
  red = 0;
  green = 0x1F;
  blue = amplit;
  break;
  case 3: 
  red = 0xFF;
  green = 0x1F - amplit;
  blue = random(0x2F);
  break;   
  case 4:
  red = 0;
  green = 0x1F - amplit;
  blue = 0x1F;
  break;  
  }
  
return red << 11 | green << 6 | blue;
}



void printWifiStatus() {
  M5.Lcd.fillScreen(TFT_BLUE); 
  M5.Lcd.setCursor(1,1); 
  M5.Lcd.setTextSize(1); 
  M5.Lcd.setTextColor(TFT_WHITE, TFT_BLUE); 
  // print the SSID of the network you're attached to:
  M5.Lcd.print("SSID: ");
  M5.Lcd.println(WiFi.SSID());

  // print your board's IP address:
  IPAddress ip = WiFi.localIP();
  M5.Lcd.print("IP Address: ");
  M5.Lcd.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  M5.Lcd.print("signal strength (RSSI):");
  M5.Lcd.print(rssi);
  M5.Lcd.println(" dBm");
  delay(5000); 
  M5.Lcd.fillScreen(TFT_BLACK); 
  M5.Lcd.setCursor(1,1); 
}

void check_board() {
  WiFiClient client = server.available(); 
  if (client) {
    while (client.connected()) {
      if (client.available()) {
      M5.Lcd.setCursor(1,1); 
      M5.Lcd.setTextColor(random(0xFFFF));
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println();
            client.println("<!DOCTYPE html><html>");
            client.println("<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
            client.println("<link rel=\"icon\" href=\"data:,\">");
            client.println("<style>html { font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center; text-color:white; background-color: #000000;}");
            client.println("h1 { background-color:black; border: none; color: red; padding: 16px 40px;");
            client.println("p { text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer; color:white;}");
            client.println("ol { list-style-type:square;}");
            client.println("</style></head>");
            client.println("<body><h1>WhiteCat Proxy network</h1><br> <h2><font color='lightblue'>ESP32 Web Server Active</h2></font>");
            client.println("<br><p><font color='white'> ");
            client.println("My network Essid is: WhiteCat <br> My network password is: whitecat1<br>");
            client.println("At this time I am configured to act as A proxy network.<br>");
            client.println("</font></p><br>"); 
            client.println("<font color='yellow' size=20>");
            int numSsid = WiFi.scanNetworks();
            
            if (numSsid == -1) { client.println("No WiFi networks Found?<br>"); }
            if (numSsid == 0) { client.println("No WiFi networks Found Searching..<br>"); }            
            client.println("WiFi networks found!<br> ");
            client.println(".<br><ol type='I'><font color='green' size=6px>");
            for (int i = 0; i <= numSsid; i++) {
            for (int thisNet = 0; thisNet < numSsid; thisNet++) {
              client.print("<li>");
              client.print(WiFi.SSID(thisNet));
              client.print("  Signal: ");
              client.print(WiFi.RSSI(thisNet));
              client.print(" dBm");
              client.print("    Encryption:"+(WiFi.encryptionType(thisNet) == WIFI_AUTH_OPEN)?" ":"OPEN");            
              client.print("</li><br>");
            }
            }
            client.println("</font><ol><p>Scanning finished.</p>");
            client.println("</body></html>");     
       client.stop(); 
      }
    }
  }
}


// Panic payload to cover essid in a packet storm array
// Version 3.1 of our payload.
// Notes: 
// if it's not in our esp_wifi.h file: 
// typedef void (*freedom_outside_cb_t)(uint8 status);
// int wifi_register_send_pkt_freedom_cb(freedom_outside_cb_t cb);
// void wifi_unregister_send_pkt_freedom_cb(void);
// int wifi_send_pkt_freedom(uint8 *buf, int len, bool sys_seq);
 
const char ssids[] PROGMEM = {
  "🌮 Bell WiFi\n"
  "🌮 🌮 🌮 🌮\n"
  "Satoshi Nakamoto\n"
  "To the Moon!\n"
  "21.000.000 BTC\n"
  "HODL\n"
  "Money without masters\n"
  "When Lambo, Sir?\n"
  "⚡ ⚡ ⚡\n"
  "⚡ THE FLASH ⚡\n"
  "Brrrrrrrrrrrrrrr..\n"
  "Citadel Intranet\n"
  "REKT\n"
  "Read the Whitepaper\n"
  "Craig Wright is a fraud\n"
  "Buy Bitcoin\n"
  "🌝 🌝 🌝 🌝 🌝\n"
  "FUCK BANKS!\n"
  "Alice and Bob's WLAN\n"
  "PowerDIlanDO\n"
  "Be a Chad\n"
  "Covid-19+\n"
  "🚀 🚀 🚀 🚀 🚀\n"
  "HTTP 402 Payment Required\n"
  "The Times 03/Jan/2009\n"
  "The People's Money\n"
  "Bitcoin fixes this\n"
  "1 BTC = 1 BTC\n"
  "Orange coin good, number go up\n"
  "📈 📈 📈 📈 📈\n"
  "Bitcoin is \"fuck you money\"\n"
  "FOMO\n"
  "bitcoin.org\n"
  "Don't trust. Verify.\n"
  "Run a Bitcoin node\n"
  "Stacking Sats\n"
  "🕯 🕯 🕯 🕯 🕯\n"
  "Unconfiscatable\n"
  "Buy the Dip\n"
  "Lightning Network ⚡\n"
  "Be your own Bank\n"
  "DYOR\n"
  "🐱‍💻\n"
  "Hey, Hey, Hey! BitConneeeeee..\n"
  "1337 h4x0r, j0 m4n!\n"
  "BTC BTC BTC BTC BTC BTC\n"
  "In it for the technology\n"
  "Long BTC, 100x leverage\n"
  "There is a hacker here\n"
    "Click For Magic\n"
    "Being a Human bot\n"
    "C0me & Ask me 4 the passw0rd\n"
    "I Have Both Camera & WiFi\n"
    "AveΠgerZ – WiFi Wars\n"
    "Babez this 1 is just 4 U\n"
    "Being co_ol is all Mat_ters\n"
    "I Have Se_en U littering\n"
    "I Will Send U 2 the Jail\n"
    "Check Ur P0cket\n"
    "WiFi is Unavailable Only 4You!\n"
    "Mαrtin R0uter Kings WiFi\n"
    "Free WiFi For 1 Ni8 Stand\n"
    "Ur WiFi Iz Sle_eping Over\n"
    "Open the door\n"
    "Avengerz indestructible WiFi\n"
    "Penny Get Ur Own WiFi\n"
    "Dαnger Z0ne!\n"
    "Areα 51 zorks door\n"
    "De$perate HouseWiFi\n"
    "Call Me Anytimε\n"
    "1o1 Problems But Wi-Fi ain’t 1\n"
    "The Net $tarring $andra Bullock\n"
    "Save Wi-Fi save lives\n"
    "Skynet Global Defense CCTV\n"
    "DefaultmeLANs\n"
    "Stop polluting the environment.\n"
    "Wi-Fight\n"
    "Sunday,sunday,sunday\n"
    "One stop shop for your internet\n"
    "Why Not You Get Your WiFi?\n"
    "Something is at your face\n"
    "I em Under Ur Bed kid\n"
    "Pr0tected CEX\n"
    "Ermahgerd, WiFi!\n"
    "Stop staring me up\n"
    "Save water drink beer!\n"
    "Swedish Mafia Safehouse\n"
    "4 Guys 1 Router\n"
    "Smart Wi-Fi for smarttes\n"
    "Connect 4 fast Identity Theft\n"
    "Behind You\n"
    "Searching For the Network…\n"
    "Unlimited Downloading…\n"
    "Go-Go Bagget Internet\n"
    "We Don’t Load\n"
    "Wi-fi is Coming\n"
    "The Ma$ter of Whisperers\n"
    "The Brotherho_od Without LAN Er_rors\n"
    "The Ping Beyond the Wall\n"
    "The WiFi that was not promised\n"
    "The Dorni$hman’s Wi-Fi\n"
    "The Mαd Pings\n"
    "PingSlayer 2.1\n"
    "Vale of Arryn\n"
    "W!ght-Fi\n"
    "House of Black & Wi-Fi\n"
    "Ping of the West\n"
    "Brotherhood of LAN Errors\n"
    "PingsLαnding\n"
    "Browsing $trong\n"
    "The Night’s PiΠg\n"
    "Khaleesi Konnections\n"
    "Dothraki $ea\n"
    "Hot Wi\n"
    "The Cr0wnlands\n"
    "$tark 0f WinterFell\n"
    "Wi-Fi has no name\n"
    "Wi-Fire and Blood!\n"
    "House LANnister bloods\n"
    "John_Snow_Knows_Something\n"
    "Ping in the North!\n"
    "Westeros WinterNET fell\n"
    "The Ping Slayer 2.0\n"
    "Oathkeeper\n"
    "Live in the moment\n"
    "Put your mask back on\n"
    "LANnisters always pay their debts\n"
    "A Lan_nister Always Pays For Net\n"
    "WIFIght the inevitable\n"
    "The Dornishman’s WiFi\n"
    "Martell of $un$pear\n"
    "U Know Nothing LAN $now!\n"
    "Master of Wi-Fi\n"
    "Azor Wah Fai\n"
    "Fortress-of-Solitude:panic-room\n"
    "H0gsmeade\n"
    "Acci0WiFi\n"
    "R00m 0f Requirement\n"
    "Enemie$ 0f the He!r\n"
    "Flo_o Network\n"
    "Expelliarmus Ur Internet\n"
    "Blαck Link\n"
    "N0 Mugglez\n"
    "RavenClaw Com_mon R00m WiFi\n"
    "The Re$tricted $ection\n"
    "Fidelu$\n"
    "Hufflepuff Common Room\n"
    "Accio WiFi\n"
    "WIREgardium LE$$iosa\n"
    "The Secret of Dark\n"
    "Black iZ Cray\n"
    "Let The Wand Cho_ose It’s Wizard\n"
    "Hogwarts Scho_ol of Fre_e WiFi\n"
    "The Le@ky Cauldr0n\n"
    "Magic $ecure Muggle WiFi\n"
    "Magic $ecure\n"
    "Wizard AlwayZ\n"
    "Accio Internet!\n"
    "Dumbled0000re\n"
    "HA!L THE DARK L0RD\n"
    "H0rcrux\n"
    "The Guild of Krux\n"
    "Wi-Fideliu$\n"
    "The Elder Wi_Fi\n"
    "Albert0 WiFi\n"
    "Wh0mPing WiFi\n"
    "A Wizard Wireles_s\n"
    "Wizard Wireles_s\n"
    "Restricted Section 51\n"
    "Connect 2 Patronum\n"
    "Hogwarts School of WiFi & Wizardry\n"
    "Al0h0Mora\n"
    "Great Hall WiFi\n"
    "Hogwarts Expres_s\n"
    "I_Must_N0t_Tell_Lies\n"
    "Hermi0ne Grinder\n"
    "L0rd V0ldeModem\n"
    "Aloh0mora Crack the Pas_sword\n"
    "Ph0enix WiFi\n"
    "Gryffindor Common Room WiFi\n"
    "$lytherin Com_mon Ro_om WiFi\n"
    "Go Away Ur Muggle\n"
    "Chamber of $ecrets\n"
    "Abraa Kaa Daabra\n"
    "Hogwarts WiFi\n"
    "Patronus Charm\n"
    "I’m Batman\n"
    "Area 51 WACO\n"
    "2 Girls 1 cup Boy\n"
    "I am so Hungry\n"
    "Signal is Weak-as-hell\n"
    "My Password is Pass\n"
    "God is here\n"
    "Connect To Die\n"
    "UR My GF\n"
    "Internet is very painful Slow\n"
    "We are Virus\n"
    "hahaha! you have No internet\n"
    "This is Not For Everyone\n"
    "Only For Girls\n"
    "Do Not Disturb F!ing\n"
    "Unique WiFi Names\n"
    "FBI Surveillance Van #119871\n"
    "NSA Surveillance #392AF8\n"
    "NSA Surveillance #844AA7\n"
    "NSA Surveillance #732AB6\n"
    "NSA Surveillance #833AC3\n"
    "DEA Surveillance #4188A87\n"
    "DEA Surveillance Van #2288C8\n"
    "FBI Surveillance #117766\n"
    "I’m Watching You Now\n"
    "Skynet GDN\n"
    "Global Defense Skynet\n"
    "Let Me Out Of Your pron Router\n"
    "Undercover Police Car #751\n"
    "Police Car #586\n"
    "Undercover FBI Car #434\n"
    "I’m Cheating on my WiFi\n"
    "InterTubes\n"
    "Because a LANnister Never Forgets\n"
    "Never forget, expect us!\n"
    "Occam’s Router box\n"
    "New England Clam Router\n"
    "Please Click For Identity Theft\n"
    "Clinternet zone\n"
    "Anonymous WiFi\n"
    "I Can Haz the Wireless?\n"
    "IP Freely LANs\n"
    "Internet Access\n"
    "NSA Net Secure\n"
    "Really Untrusted Network\n"
    "Untrusted WiFi\n"
    "Virus Detected! Do Not Join\n"
    "Malware Repository\n"
    "Maleware thunb drive\n"
    "WiFi Ducky\n"
    "Access Denied fool\n"
    "Uncle_Touchys_Game_Room\n"
    "IP-UP-LAN-IP-I\n"
    "YerBabyIsReallyFat\n"
    "John Wilkes WiFi\n"
    "Slow WiFi\n"
    "Iron Ducky here\n"
    "1Optimus Prime\n"
    "WamBamThankYouLan\n"
    "TellMyWiFiLoveHer\n"
  "Under Your Ded now\n"
  "I'am under the bar\n"
  "LOLZ/b/Random\n"
  "http://www.4chan.org\n"
  "8chan.org\n"
  "Mom Use This One\n"
  "InyourWheelHouse\n"
  "Bro, get-off-my pornbox\n"
  "Brah! use this one\n"
  "Abraham Linksys\n"
  "No More fake news!\n"
  "Welcome back MAGA\n"
  "Biden is god\n"
  "Benjamin FrankLAN\n"
  "Biden is evil \n"
  "Inferno Peanuts\n"
  "HOT&SPICY\n"
  "999SATAN666\n"
  "I am in your car\n"
  "Zardos, The Spam is good!\n"
  "HerBack Door pass\n"
  "Bitches Gone WiFi\n"
  "bro in your van\n"
  "The Gang gets WiFi\n"
  "CapsLock is on\n"
  "In your car\n"
  "POP the trunk\n"
  "Dump Trump\n"
  "Hack loading ..\n"
  "infowarsstoree.com\n"
  "Rocket WiFi 10Kbps\n"
  "Pocket Rocket \n"
  "Glory Hole WiFi\n"
  "Pool-Pocket pro\n"
  "#BlackDicksMatter\n"
  "Martin Router King\n"
  "John Wilkes Bluetooth\n"
  "Pretty Fly for a Wi-Fi\n"
  "Bill Wi the Science Fi\n"
  "I Believe Wi Can Fi\n"
  "Tell My Wi-Fi Love Her\n"
  "No More Mister Wi-Fi\n"
  "LAN Solo\n"
  "I AM LAN LOCKED\n"
  "The LAN Before Time\n"
  "Silence of the LANs\n"
  "House LANister\n"
  "Winternet Is Coming\n"
  "Ping’s Landing\n"
  "The Ping in the North\n"
  "This LAN Is My LAN\n"
  "Get Off My LAN\n"
  "SUPERvised LAN\n"
  "The Promised LAN\n"
  "The LAN Down Under\n"
  "FBI Surveillance Van 4\n"
  "Area 51 Test Site\n"
  "Drive-By Wi-Fi\n"
  "Planet Express\n"
  "Wu Tang LAN\n"
  "Darude LANstorm\n"
  "Never Gonna Give You Up\n"
  "Hide Yo Kids, Hide Yo Wi-Fi\n"
  "Loading…\n"
  "Searching…\n"
  "VIRUS.EXE\n"
  "1% 2% 3%\n"
  "Virus-Infected Wi-Fi\n"
  "Starbucks Wi-Fi\n"
  "Text ###-#### for Password\n"
  "Yell ____ for Password\n"
  "The Password Is 1234\n"
  "Free Public Wi-Fi\n"
  "No Free Wi-Fi Here\n"
  "Get Your Own Damn Wi-Fi\n"
  "It Hurts When IP\n"
  "Dora the Internet Explorer\n"
  "404 Wi-Fi Unavailable\n"
  "Porque-Fi\n"
  "Titanic Syncing\n"
  "Test Wi-Fi Please Ignore\n"
  "Drop It Like It’s Hotspot\n"
  "Life in the Fast LAN\n"
  "The Creep Next Door\n"
  "Ye Olde Internet\n"
  "Mother lan FUCKERS \n"
  "RockHard LAN\n"
  "cocksuckers\n"
  "MikeShesCheatingOnYou\n"
  "1Kpbs Speed\n"
  "LAN Down UNDER baby\n"
  "TwoWhiteBitches\n"
  "Infected WiFi\n"
  "Titanic Synching\n"
  "Click-Here-for-free-virus\n"
  "disabled SSID\n"
  "I Pronounce you Man and WiFI\n"
  "I did your Wifi Last Night\n"
  "Happy Wifi Happy Life!\n"
  "$10 per hour\n"
  "PornTorrent max\n"
  "PornBox\n"
  "Beer and bitches bro!\n"
  "AOL Dialup\n"
  "TheodoreFrankLAN\n"
  "Vladimir Routin\n"
  "Your WiFi has COVID-19\n"
  "John-Claude-WAN-Damme\n"
  "FreeSpeechZone\n"
  "I am Iron LAN\n"
  "Spider LAN, Spider LAN\n"
  "DoLAN Trump\n"
  "404 Wi-Fi Unavailable\n"
  "Virus Distribution Center\n"
  "your Dog shits in my yard\n"
  "Free WiFi, Just Kidding\n"
  "your mesic is annoying\n"
  "infowars.com\n"
  "prisonplanet.tv\n"
  "poor boy signal\n"
  "No Facebook, Happy Life\n"
  "Hey! We can hear U while S*x\n"
  "Making Wi-Fi Great Once Again\n"
  "vladimir computin\n"
  "WiMCA\n"
  "1000100001111011111101111\n"
  "1110111011101110111011101\n"
  "I0I 101\n"
  "www.Pornhub.com\n"
  "Free Dick pics?\n"
  "1000mbps add for me losers\n"
  "GetOffMyLAN\n"
  "I can hear you Farting!\n"
  "Immigration Authorities\n"
  "NiceTryNeighbor\n"
  "TheBotZareWatchingYou\n"
  "www.4chan.org\n"
  "Pay berfore you Digi-dump\n"
  "Hacking your WiFi !\n"
  "CCTV Bathroom mens\n"
  "CCTV Bathroom hidden\n"
  "FBI Van A0938EG\n"
  "MAGA Trump4MoreYRS\n"
  "FU-BAR-WiFi\n"
  "Gitchers WiFi\n"
  "Golden-WiFi\n"
  "Loser-retard-wifi\n"
  "LAN of the lost\n"
  "LanHansel1\n"
  "your-moms-backdoor\n"
    "Promised WiFi Power Range\n"
    "We_don’t_have_any_WiFi\n"
    "Hαppiness is When Ü know them.\n"
    "Lazy sloth Internet!\n"
    "Yell [Pene$] 4 Password\n"
    "No More WiFi man\n"
    "Everytime em Buffering\n"
    "Password Free\n"
    "N0 Pant$ N0 Problem$\n"
    "GirlZz G⍥NE Wireless ?\n"
    "Hilαry Clint£rnet\n"
    "Mine Number 09000000\n"
    "∞ Speed\n"
    "Bill Wi, the $cience Fi\n"
    "Traffic Sucker ?\n"
    "WinTernet I$ Here ❄️\n"
    "Loading Failed\n"
    "BobZ Un$ecured Hou$e of WiFi\n"
    "Con_nect 2 Die\n"
    "Troy & Abed in the Modem$\n"
    "Fear of dogs\n"
    "A co_ol head and glowing Wi-Fi\n"
    "Only Your WiFi\n"
    "It Really βurns When IP ?\n"
    "Get off My LANss!\n"
    "Restricted Section\n"
    "Property of mine \n"
    "sexy girlfriend only ?\n"
    "Go_od WiFi\n"
    "Fre_e WiFi Available Here\n"
    "The LAN βefore Time\n"
    "Nacho lebray WiFi\n"
    "Huh next time secure your router\n"
    "Fre_e WiFi\n"
    "Fly for a WiFi\n"
    "Get Ur OwNET Bruh\n"
    "Only for my sexy wife\n"
    "M00CHES WIFI\n"
    "Dora The Internet Explorer\n"
    "Stop Being A M00ch\n"
    "Good Wi-Fi c00l extra than cold water\n"
    "Bens WiFi\n"
    "Obtaining the IP Address\n"
    "424: Wi-Fi Unavailable\n"
    "Choose a Network already\n"
    "Waiting for the connection\n"
    "Unknown Device\n"
    "Connecting to yahoo…\n"
    "Router Failure\n"
    "IP Connection Refused\n"
    "Unavailable Now\n"
    "Prohibited suckers\n"
    "The awesome reset\n"
    "No Networks Available\n"
    "Incorrect password entered\n"
    "Error: Please Contact Your ISP\n"
    "Direct Satellite Home Transfer\n"
    "TCP/IP ERROR 42\n"
    "Setting upppp\n"
    "Testing stupid idea\n"
    "Signing Off\n"
    "Server Error falt\n"
    "Connection Out\n"
    "Qwest timed out\n"
    "Searching…...\n"
    "Loading…...\n"
    "Need Antivirus Software\n"
    "Use at your own risk\n"
    "Yo Access Denied!\n"
    "Under Maintenance\n"
    "You have been blocked\n"
    "Not In Use\n"
    "internet connectivity\n"
    "Network_Error_410\n"
    "168.1.1\n"
    "192.168.1.4\n"
    "Connection Lost\n"
    "Network is down\n"
    "Airplane Mode Active\n"
    "DHCP_Failure_Error\n"
    "Device Battery Low\n"
    "Shutting Down shit\n"
    "Service Interrupted\n"
    "Noooooo.Disconnected\n"
    "Dial-up 56k Internet\n"
    "RFID Tag Reader\n"
    "dns_unresolved_hostname\n"
    "Limit Exceeded retard\n"
    "Signals not found\n"
    "Gateway 666 Error\n"
    "Searching for network dork!\n"
    "Android Bluetooth\n"
    "Router Malfunction\n"
    "Device Damaged\n"
    "Bean falls down\n"
    "My Wi-FI Love Her\n"
    "Can I be Frank LAN\n"
    "Area 51 B Test Site\n"
    "The Creeps pron LAN\n"
    "Get Your Own Wi-Fi\n"
    "wireless gang bang 2\n"
    "NOTFree Public Wi-Fi\n"
    "Yell help for Password\n"
    "Starbucks Wi-Fi front\n"
    "The Legion of Doom\n"
    "That’s HotSpot\n"
    "Porque-Fi\n"
    "LANdo\n"
    "Yummy!!\n"
    "The Notorious R.P.G.\n"
    "No, Mo-More Mister Wi-Fi\n"
    "The Password Is 1234\n"
    "Why do you get WiFi?\n"
    "LANister?\n"
    "The Deathstar WiFi\n"
    "The Banana Stand\n"
    "ye-old LANs\n"
    "Wi-Fi Please Ignore\n"
    "Never Gonna Give You Up!!\n"
    "No Free Wi-Fi \n"
    "Text 406-###-#### for Password\n"
    "404 Sllooww Wi-Fi Unavailable\n"
    "It Hurts When IP LAN\n"
    "Life in the Fast LAN 2.0\n"
    "GeoLANstorm\n"
    "FBI Surveillance Van 34E4AS\n"
    "The Ping in the North\n"
    "Wi-fight the inevitable\n"
    "wireless router.\n"
    "WORLD tour\n"
    "Ping’s LANding\n"
    "EXE\n"
    "Dora the Internet Explorer 2\n"
    "Virus-Infected Wi-Fi 2\n"
    "This LAN Is My LAN 2\n"
    "Total Hear\n"
    "Ye Olde Internet 2\n"
    "no, this is not free either\n"
    "Silence of the LANsss\n"
    "I Believe Wi Can Fi\n"
    "1UP Mushroom\n"
    "2Girls1Dorm\n"
    "And I Thought They Smelled Bad On The Outside\n"
    "Andromeda\n"
    "At least I get laid loser\n"
    "BeyHive\n"
    "Bill Wi the Science Fi 2\n"
    "Bill! Bill! Bill! Bill! Bill!\n"
    "Bluth Company\n"
    "Bowser’s Castle\n"
    "Close your blinds, dude!\n"
    "Don’t look under the bed\n"
    "Drop It Like Its HotSpot\n"
    "Dunder-Mifflin\n"
    "DungeonMaster\n"
    "Ermahgerd Wer Fer\n"
    "Fortress of Solitude\n"
    "Getyourownnetbro\n"
    "GucciLouisPrada\n"
    "Hall of Justice\n"
    "Hide Yo, Hide Yo Wifi\n"
    "I Got 99 Problems But WiFi Ain’t 1\n"
    "I killed your cat\n"
    "I Spy With WiFi\n"
    "I watch you guys all night\n"
    "Icanseeyourightnow\n"
    "the Rat hole \n"
    "Dirty carbon unit\n"
    "ImUnderYourBed\n"
    "InternetCosts$\n"
    "I’mRickJamesB!tch\n"
    "I’ve Seen You Naked\n"
    "Jabba the Hut’s Lair\n"
    "JumpmanJumpmanJumpman\n"
    "Keep It On The Download\n"
    "Krypton\n"
    "LanDownUnderBro!\n"
    "Lansanity\n"
    "gather for Jesus\n"
    "MakeAmericaGreatWithFreeWiFiAgain\n"
    "Millennium Falcon\n"
    "No Wifi For You geeky!\n"
    "NoFreeInternetHereKeepLooking\n"
    "NotMyPresident\n"
    "Notthedroidsyouarelookingfor\n"
    "One Does Not Simply Use WiFi\n"
    "One Small Step For Man, One Giant Leap For WiFi\n"
    "Parks and Recreation WiFi\n"
    "The shitters WiFi\n"
    "KABOOOM!\n"
    "FUCK-IT!\n"
    "Hit-me-in-the-bum-bum\n"
    "Iron Lan Man\n"
    "IronDucky HanSel 2\n"
    "Iron Ducky 54\n"
    "InCEL 4 life\n"
    "Iron Ducky 33\n"
    "I am IRON LAN 2\n"
    "Iron Ducky*\n"
    "I computer lab\n"
    "Icon Public WiFi\n"
    "Space Invader\n"
    "32bitGameBoy\n"
    "8bit duck hunter\n"
    "TurboRouters\n"
    "WhitehotBlackText\n"
    "QuackDucky\n"
    "192.168.0.1\n"
    "192.168.1.1\n"
    "Its HAM RADIO\n"
    "DevilDucky\n"
    "192.168.2.2\n"
    "Its the cops run!\n"
    "RubberyDucky\n"
    "QC to CQ \n"
    "IDucky2\n"
    "192.168.3.1\n"
    "Liberal protest\n"
    "IronDucky\n"
    "InternetRA!\n"
    "666 SATAN 999\n"
    "Evil WiFi \n"
    "Alien 1\n"
    "Aliens 2\n"
    "192.168.2.5\n"
    "192.168.4.4\n"
    "Alien 3\n"
    "Springs WiFi\n"
    "P0Wn3D WiFi\n" 
    "192.168.1.19\n"    
    "172.196.4.23\n"
    "192.168.10.111\n"    
    "192.168.211.234\n"
    "192.168.21.90\n"
    "WiFin\n"
    "GaTeS_CrUsHeR\n"
};
